### ISSUE TITLE
Error: Unsupported operation: ServerSocket.bind

### ISSUE THREAD

**Issue by zhuyonghao** [dart-lang/shelf_proxy#19]
Error: Unsupported operation: ServerSocket.bind
    at Object.throw_ [as throw] (http://localhost:50675/dart_sdk.js:4339:11)
    at Function._bind (http://localhost:50675/dart_sdk.js:57307:17)
    at Function.bind (http://localhost:50675/dart_sdk.js:57295:32)
    at Function.bind (http://localhost:50675/dart_sdk.js:183998:30)
    at Function.bind (http://localhost:50675/dart_sdk.js:177277:32)
    at serve (http://localhost:50675/packages/shelf/src/io_server.dart.lib.js:130:70)
    at serve.next (<anonymous>)
    at runBody (http://localhost:50675/dart_sdk.js:37699:34)
    at Object._async [as async] (http://localhost:50675/dart_sdk.js:37730:7)
    at Object.serve (http://localhost:50675/packages/shelf/src/io_server.dart.lib.js:128:18)
    at main$ (http://localhost:50675/packages/flutter_demo_vmcshop_app/main.dart.lib.js:461:36)
    at main$.next (<anonymous>)
    at runBody (http://localhost:50675/dart_sdk.js:37699:34)
    at Object._async [as async] (http://localhost:50675/dart_sdk.js:37730:7)
    at main$ (http://localhost:50675/packages/flutter_demo_vmcshop_app/main.dart.lib.js:460:18)
    at main (http://localhost:50675/web_entrypoint.dart.lib.js:34:27)
    at main.next (<anonymous>)
    at http://localhost:50675/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:50675/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50675/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:50675/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:50675/dart_sdk.js:33092:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50675/dart_sdk.js:32818:27)
    at Object._microtaskLoop (http://localhost:50675/dart_sdk.js:37794:13)
    at _startMicrotaskLoop (http://localhost:50675/dart_sdk.js:37800:13)
    at http://localhost:50675/dart_sdk.js:33309:9

**Comment by StarkZzzOoo** [comment]
me too
